Repository HangHae-TheFinalProject/FrontEnd, pull requests merged in 2022-12, with the labels that each got.

#115 정건희: <refactor> chat 불필요한 console.log 주석 및 컴포넌트 삭제
  src/components/chat/Chat.jsx
  src/components/chatRoom/ChatRoom.jsx
  src/components/chatRoom/style.scss
  src/components/chatRoomList/ChatRoomList.jsx
Labels: ⛏Refactor

#116 신혜정 : <feature> 게시판 기능 구현 중
  src/components/community/communityCard/CommunityCard.jsx
  src/components/community/communityCard/style.scss
  src/components/community/communityDetail/CommunityDetail.jsx
  src/components/community/communityDetail/style.scss
  src/components/community/communityFix/CommunityFix.jsx
  src/components/community/communityFix/style.scss
  src/components/community/communityList/CommunityList.jsx
  src/components/community/communityList/style.scss
  src/components/community/communityWrite/CommunityWrite.jsx
  src/components/community/communityWrite/style.scss
  src/images/png/communityBox.png
  src/images/png/detailBack.png
  src/images/png/writeImg.png
  src/images/svg/DeleteIcon.svg
  src/images/svg/DropBoxIconDown.svg
  src/images/svg/FixIcon.svg
  src/images/svg/PageBtnIconL.svg
  src/images/svg/PageBtnIconR.svg
  src/images/svg/PenIcon.svg
  src/images/svg/SearchIcon.svg
  src/pages/social/Detail.jsx
  src/pages/social/List.jsx
  src/pages/social/Write.jsx
  src/shared/Router.jsx
Labels: ✨Feature

#121 신혜정 : <Style> select박스 디자인 반영
  src/components/roomList/RoomList.jsx
  src/components/roomList/style.scss
Labels: 🎨HTML&CSS

#124 김민주: <fix> 게시판 페이징&정렬
  src/components/community/communityCard/CommunityCard.jsx
  src/components/community/communityList/CommunityList.jsx
  src/components/community/communityList/style.scss
  src/components/community/communityWrite/CommunityWrite.jsx
  src/pages/social/List.jsx
  src/pages/social/Social.jsx
  src/shared/Router.jsx
Labels: 🐞Bug

#122 정건희: <refactor> chat 입장메세지 난수 제거된 닉네임 사용, 그 외에는 난수 포함된 메세지 전송
  src/components/chat/Chat.jsx
Labels: ⛏Refactor

#123 정건희: <style> 로그인, 회원가입 css 수정 적용
  src/components/formSignIn/FormSignIn.jsx
  src/components/formSignIn/style.scss
  src/components/formSignUp/FormSignUp.jsx
  src/components/formSignUp/style.scss
  src/components/googleLogin/GoogleLogin.jsx
  src/components/googleLogin/style.scss
  src/components/sign/formSignIn/FormSignIn.jsx
  src/components/sign/formSignIn/style.scss
  src/components/sign/formSignUp/FormSignUp.jsx
  src/components/sign/formSignUp/style.scss
  src/components/sign/googleLogin/GoogleLogin.jsx
  src/components/sign/googleLogin/style.scss
  src/components/temp_sign/TempSign.jsx
  src/components/temp_sign/style.scss
  src/images/png/gameRoomBackground.png
  src/images/png/gameTitleBakcground.png
  src/images/svg/GoogleLoginBtn.svg
  src/images/svg/Greenicon.svg
  src/images/svg/gameTitle.svg
  src/pages/Main.jsx
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
Labels: 🎨HTML&CSS

#125 정건희: <style> 마이페이지 svg > png 교체, 전적 데이터 반영
  src/components/myPage/myPageForm/MyPageForm.jsx
  src/components/myPage/myPageForm/style.scss
  src/components/myPage/myPageRecord/MyPageRecord.jsx
  src/images/png/myPage_ActiveBtn.png
  src/images/png/myPage_Frame.png
  src/images/png/myPage_InActiveBtn.png
  src/images/svg/myPage_ActiveBtn.svg
  src/images/svg/myPage_Frame.svg
  src/images/svg/myPage_InActiveBtn.svg
Labels: 🎨HTML&CSS

#126 김민주: <fix> 왕관표시 오류 수정
  src/components/videoroom/video/Video.js
Labels: 🐞Bug

#136 정건희: < style> Lobby 방만들기 모달 창 css 수정, 불필요한 컴포넌트 삭제
  src/components/createRoomForm/CreateRoomForm.jsx
  src/components/createRoomForm/style.scss
  src/images/png/createRoomModalBackground.png
  src/pages/social/Social.jsx
  src/pages/social/style.scss
Labels: 🎨HTML&CSS

#138 김민주: <setting> 환경변수 세팅 #131
  .gitignore
  src/components/chat/Chat.jsx
  src/components/sign/googleLogin/GoogleLogin.jsx
  src/components/videoroom/videoRoom/VideoRoom.js
  src/pages/gameroom/GameRoom.jsx
  src/shared/Request.js
Labels: ⚙Setting

#139 정건희: <fix> 구글 로그인
  .gitignore
  src/components/sign/googleLogin/GoogleLogin.jsx
Labels: 🐞Bug, ⚙Setting

#143 신혜정 : <feature> 게시판 기능 수정, 검색 기능 추가 등
  src/components/community/communityCard/CommunityCard.jsx
  src/components/community/communityDetail/CommunityDetail.jsx
  src/components/community/communityFix/CommunityFix.jsx
  src/components/community/communityFix/style.scss
  src/components/community/communityList/CommunityList.jsx
  src/components/community/communityList/style.scss
  src/components/roomList/style.scss
Labels: ✨Feature

#144 정건희: <style> Lobby 배경화면, 헤더 css 수정
  .gitignore
  src/components/createRoomForm/CreateRoomForm.jsx
  src/components/lobbyHeader/LobbyHeader.jsx
  src/components/lobbyHeader/style.scss
  src/components/socialHeader/SocialHeader.jsx
  src/components/socialHeader/style.scss
  src/pages/lobby/style.scss
Labels: 🎨HTML&CSS

#147 정건희: <feature> 마이페이지 플레이 시간 style 수정
  src/components/myPage/myPageForm/MyPageForm.jsx
Labels: ⛏Refactor

#152 신혜정 : <style> GameRoom 닉네임 줄 바꿈 금지 설정
  src/components/gamePopup/style.scss
Labels: 🎨HTML&CSS

#151 정건희: <fix> Lobby css 수정
  src/pages/lobby/style.scss
Labels: 🎨HTML&CSS

#163 김민주: <feature> subscribe 주소 추가
  src/pages/gameroom/GameRoom.jsx
Labels: 📬API

#154 정건희: <style> chat 스크롤 바 css 적용
  src/components/chat/style.scss
Labels: 🎨HTML&CSS

#156 정건희: <style> 로그인, 회원가입 버튼 css 수정 적용
  src/components/sign/formSignIn/style.scss
  src/components/sign/formSignUp/style.scss
Labels: 🎨HTML&CSS

#158 정건희: <style> Lobby 폰트 및 간격 css 수정 적용
  src/components/aRoom/ARoom.jsx
  src/components/aRoom/style.scss
  src/components/createRoomForm/style.scss
  src/components/lobbyHeader/style.scss
  src/components/roomList/RoomList.jsx
  src/components/roomList/style.scss
  src/components/socialHeader/style.scss
  src/pages/lobby/Lobby.jsx
  src/pages/lobby/style.scss
Labels: 🎨HTML&CSS

#161 신혜정 : <Style> lobby 드롭 박스 메뉴 스타일 적용
  src/components/community/communityList/CommunityList.jsx
  src/components/roomList/RoomList.jsx
  src/components/roomList/style.scss
Labels: 🎨HTML&CSS

#162 신혜정 : <Fix> search 에러 얼럿 수정
  src/components/community/communityList/CommunityList.jsx
Labels: 🐞Bug

#166 김민주: <feature> 비디오, 마이크 on/off 기능 추가 및 비디오 off 시 캐릭터 노출
  src/components/videoroom/video/Video.js
  src/components/videoroom/video/style.scss
  src/components/videoroom/videoRoom/VideoRoom.js
  src/images/png/characters/elliot.png
  src/images/png/characters/george.png
  src/images/png/characters/harry.png
  src/images/png/characters/jack.png
  src/images/png/characters/jaina.png
  src/images/png/characters/oliver.png
  src/images/png/characters/serena.png
  src/images/png/characters/susan.png
  src/images/png/iconMicOff.png
  src/images/png/iconMicOn.png
  src/images/png/iconVideoOff.png
  src/images/png/iconVideoOn.png
  src/pages/gameroom/GameRoom.jsx
  src/pages/gameroom/style.scss
Labels: ✨Feature

#167 김민주: <fix> conflict error
  src/pages/gameroom/GameRoom.jsx
Labels: 🐞Bug

#168 정건희: <style> 방장 왕관 위치 변경
  src/components/videoroom/video/style.scss
Labels: 🎨HTML&CSS

#165 정건희: <style> 게시판 css 수정 적용
  src/components/comments/commentsForm/style.scss
  src/components/community/communityCard/CommunityCard.jsx
  src/components/community/communityCard/style.scss
  src/components/community/communityDetail/CommunityDetail.jsx
  src/components/community/communityDetail/style.scss
  src/components/community/communityFix/CommunityFix.jsx
  src/components/community/communityList/CommunityList.jsx
  src/components/community/communityList/style.scss
  src/images/png/detailBack.png
  src/images/svg/PenIcon.svg
  src/images/svg/SearchIcon.svg
  src/pages/social/Detail.jsx
  src/pages/social/List.jsx
  src/pages/social/Write.jsx
Labels: 🎨HTML&CSS

#169 김민주: <fix> 게시글 공란으로 작성이 불가하도록 예외처리
  src/components/community/communityWrite/CommunityWrite.jsx
Labels: 🐞Bug

#170 김민주: <feature> 게임 중 나간 경우 예외처리
  src/pages/gameroom/GameRoom.jsx
  src/redux/modules/gameSlice.js
  src/redux/modules/roomsSlice.js
Labels: ✨Feature

#172 정건희: <style> Lobby 드롭 박스 위치 정렬 수정
  src/components/community/communityList/style.scss
  src/components/roomList/RoomList.jsx
  src/components/roomList/style.scss
Labels: 🎨HTML&CSS

#175 김민주: <fix> 로그아웃/탈퇴 후 instance header 변경되지 않는 오류 수정
  src/shared/Request.js
Labels: 🐞Bug

#176 김민주: <fix> DB에 없는 방에 입장할 수 없도록 예외처리
  src/pages/gameroom/GameRoom.jsx
Labels: 🐞Bug

#178 정건희: <setting> 배포 버전에서 devtool 접속 차단
  package.json
  src/App.js
  src/index.js
  src/redux/config/configStore.js
  src/registerServiceWorker.js
Labels: ⚙Setting

#179 김민주: <api> API 명세서 변경에 따른 업데이트
  src/components/myPage/myPageForm/MyPageForm.jsx
  src/components/myPage/myPageReward/MyPageReward.jsx
  src/components/myPage/myPageReward/rewardList.json
  src/components/myPage/myPageRewardItem/MyPageRewardItem.jsx
Labels: 📬API

#181 김민주: <fix> 회원가입/로그인 시 header 없는 instance 사용
  src/components/sign/formSignIn/FormSignIn.jsx
  src/components/sign/formSignUp/FormSignUp.jsx
Labels: 🐞Bug

#184 김민주: <style> favicon, title 변경
  public/favicon.ico
  public/index.html
Labels: 🎨HTML&CSS

#185 김민주: <style> Ready 버튼 정렬 수정 #182
  src/components/videoroom/video/Video.js
Labels: 🎨HTML&CSS

#187 김민주: <refactor> console.log 삭제
  src/components/chat/Chat.jsx
  src/components/comments/commentItem/CommentItem.jsx
  src/components/comments/commentPost/CommentPost.jsx
  src/components/community/communityCard/CommunityCard.jsx
  src/components/community/communityDetail/CommunityDetail.jsx
  src/components/community/communityFix/CommunityFix.jsx
  src/components/community/communityList/CommunityList.jsx
  src/components/community/communityWrite/CommunityWrite.jsx
  src/components/gamePopup/GamePopup.jsx
  src/components/roomList/RoomList.jsx
  src/components/videoroom/videoRoom/VideoRoom.js
  src/pages/gameroom/GameRoom.jsx
  src/pages/lobby/Lobby.jsx
Labels: ⛏Refactor

#190 김민주: <feature> add Sentry
  package.json
  src/index.js
Labels: ✨Feature

#192 김민주: <feature> 게임 시작 인원 제한
  src/pages/gameroom/GameRoom.jsx
Labels: ✨Feature

#193 Deploy
  src/pages/gameroom/GameRoom.jsx
Labels: 🌏Deploy

#194 김민주: <deploy> Spotlight Time 변경
  src/pages/gameroom/GameRoom.jsx
Labels: 🌏Deploy

#195 Develop
  src/pages/gameroom/GameRoom.jsx
Labels: 🌏Deploy

#197 정건희: <fix> 댓글 수정
  src/components/comments/commentItem/CommentItem.jsx
  src/components/comments/commentPost/CommentPost.jsx
  src/components/community/communityCard/CommunityCard.jsx
  src/components/community/communityDetail/CommunityDetail.jsx
  src/components/community/communityFix/CommunityFix.jsx
  src/components/community/communityList/CommunityList.jsx
  src/components/community/communityWrite/CommunityWrite.jsx
Labels: 🐞Bug

#201 김민주: <fix> 브라우저 종료 시 leaveRoom API 호출되지않는 오류 수정
  src/pages/gameroom/GameRoom.jsx
Labels: 🐞Bug

#202 정건희: <fix> 댓글 수정 replace error 수정
  src/components/comments/commentItem/CommentItem.jsx
  src/components/community/communityDetail/CommunityDetail.jsx
  src/images/svg/PenIcon.svg
  src/images/svg/SearchIcon.svg
Labels: 🐞Bug

#203 Deploy
  src/components/comments/commentItem/CommentItem.jsx
  src/components/community/communityDetail/CommunityDetail.jsx
  src/images/svg/PenIcon.svg
  src/images/svg/SearchIcon.svg
  src/pages/gameroom/GameRoom.jsx
Labels: 🌏Deploy

#206 Deploy
  src/components/comments/commentItem/CommentItem.jsx
  src/components/comments/commentPost/CommentPost.jsx
  src/components/community/communityDetail/CommunityDetail.jsx
  src/components/community/communityDetail/style.scss
  src/components/community/communityFix/CommunityFix.jsx
Labels: 🌏Deploy

#205 김민주: <refactor> videoroom 함수정리/변수명통일
  src/components/videoroom/video/Video.js
  src/components/videoroom/videoRoom/VideoRoom.js
  src/components/videoroom/videoRoom/userModel.js
  src/pages/gameroom/GameRoom.jsx
Labels: ⛏Refactor

#207 김민주: <fix> mic & Cam Icon
  src/components/videoroom/videoRoom/VideoRoom.js
  src/components/videoroom/videoRoom/style.scss
  src/pages/gameroom/GameRoom.jsx
  src/pages/gameroom/style.scss
Labels: 🐞Bug

#208 김민주: <fix> Device loading 처리
  src/components/videoroom/videoRoom/VideoRoom.js
  src/pages/gameroom/GameRoom.jsx
Labels: 🐞Bug

#209 김민주: <style> video 정렬 수정
  src/components/videoroom/videoRoom/VideoRoom.js
  src/components/videoroom/videoRoom/style.scss
Labels: 🎨HTML&CSS

#210 Deplay
  src/components/videoroom/video/Video.js
  src/components/videoroom/videoRoom/VideoRoom.js
  src/components/videoroom/videoRoom/style.scss
  src/components/videoroom/videoRoom/userModel.js
  src/pages/gameroom/GameRoom.jsx
  src/pages/gameroom/style.scss
Labels: 🌏Deploy

#211 김민주: <fix> 입장 후 Owner 정보 표시 오류 수정
  src/pages/gameroom/GameRoom.jsx
Labels: 🐞Bug

#212 Deploy
  src/pages/gameroom/GameRoom.jsx
Labels: 🌏Deploy

#213 김민주: <fix> Liar Board 내용 표시 오류 수정
  src/pages/gameroom/GameRoom.jsx
Labels: 🐞Bug

#215 김민주: <fix> 바보모드 라이어일 때 오류 수정
  src/components/gameBoard/GameBoard.jsx
Labels: 🐞Bug

#216 김민주: <fix> 바보모드에서 라이어 보드 재 수정
  src/components/aRoom/ARoom.jsx
  src/components/gameBoard/GameBoard.jsx
  src/pages/gameroom/GameRoom.jsx
  src/redux/config/configStore.js
  src/redux/modules/roomsSlice.js
Labels: 🐞Bug

#218 김민주: <fix> 게시글 수정 시 값이 입력되어있음에도 인식되지 않는 오류 수정
  src/components/community/communityFix/CommunityFix.jsx
Labels: 🐞Bug

#219 Deploy
  src/components/community/communityFix/CommunityFix.jsx
Labels: 🌏Deploy

#223 Develop
  src/pages/gameroom/GameRoom.jsx
Labels: 🌏Deploy

#224 김민주: <style> 게임보드 멘션 일부 변경
  src/components/gameBoard/GameBoard.jsx
  src/pages/gameroom/GameRoom.jsx
Labels: 🎨HTML&CSS

#226 feature/Notice 페이지 추가
  src/pages/notice/Notice.jsx
  src/pages/notice/style.scss
Labels: ✨Feature

#227 Deploy
  src/pages/notice/Notice.jsx
  src/pages/notice/style.scss
Labels: 🌏Deploy

#228 김민주: <fix> 회원탈퇴 시 헤더가 전달되지 않는 오류 수정
  src/components/myPage/myPageSignOut/MyPageSignOut.jsx
Labels: 🐞Bug

#229 Deploy
  src/components/myPage/myPageSignOut/MyPageSignOut.jsx
Labels: 🌏Deploy

#230 김민주: <fix> 구글 회원탈퇴 오류 수정
  src/components/myPage/myPageSignOff/MyPageSignOff.jsx
  src/components/myPage/myPageSignOut/MyPageSignOut.jsx
Labels: 🐞Bug

#231 Deploy
  src/components/myPage/myPageSignOff/MyPageSignOff.jsx
  src/components/myPage/myPageSignOut/MyPageSignOut.jsx
Labels: 🌏Deploy

#233 정건희: <fix> GameRoom 코드 메인 기준으로 새로 커밋
  src/pages/gameroom/GameRoom.jsx
Labels: 🐞Bug

#235 김민주: <fix> Gameboard 수정
  src/components/gameBoard/GameBoard.jsx
  src/pages/gameroom/GameRoom.jsx
Labels: 🐞Bug

#238 김민주: <fix> 입장 직후 GameBoard오류 수정
  src/pages/gameroom/GameRoom.jsx
Labels: 🐞Bug

#245 김민주: <fix> console 추가
  src/pages/gameroom/GameRoom.jsx
Labels: 🐞Bug

#246 김민주: <fix> endgame popup
  src/components/gamePopup/GamePopup.jsx
  src/components/videoroom/videoRoom/VideoRoom.js
Labels: 🐞Bug

#247 김민주: <fix> console log 제거
  src/pages/gameroom/GameRoom.jsx
Labels: 🐞Bug

#249 정건희: <style> 댓글 목록, 게임 룰 공지 추가
  src/components/community/communityCard/CommunityCard.jsx
  src/components/community/communityCard/style.scss
  src/components/community/communityFix/CommunityFix.jsx
  src/components/community/communityList/CommunityList.jsx
  src/components/community/communityList/style.scss
  src/components/gameRuleBoard/GameRuleBoard.jsx
  src/components/gameRuleBoard/style.scss
  src/components/lobbyHeader/LobbyHeader.jsx
  src/components/lobbyHeader/style.scss
  src/components/roomList/RoomList.jsx
  src/components/roomList/style.scss
  src/components/setting/SettingBoard.jsx
  src/components/setting/style.scss
  src/components/socialHeader/DetailSocialHeader.jsx
  src/components/socialHeader/SocialHeader.jsx
  src/images/png/gameRuleFrame.png
  src/images/png/settingFrame.png
  src/images/svg/icCommentsIcon.svg
  src/images/svg/icQuestion.svg
  src/pages/social/Write.jsx
Labels: 🎨HTML&CSS

#250 정건희: <style> 생성된 방이 없습니다. 문구 추가
  src/components/roomList/RoomList.jsx
  src/components/roomList/style.scss
Labels: 🎨HTML&CSS

#251 김민주: <refactor> 일부 리소스 svg > png 변경
  src/components/chat/Chat.jsx
  src/components/gameBoard/GameBoard.jsx
  src/components/sign/formSignIn/FormSignIn.jsx
  src/components/videoroom/video/Video.js
  src/images/png/chatOutputBox.png
  src/images/png/crown.png
  src/images/png/gameBoardFrame.png
  src/images/png/gameTitle.png
  src/images/rooms/room_01.jpg
  src/images/rooms/room_02.jpg
  src/images/rooms/room_03.jpg
  src/images/rooms/room_04.jpg
  src/images/rooms/room_05.jpg
  src/images/rooms/room_06.jpg
  src/images/svg/chatOutputBox.svg
  src/images/svg/crown.svg
  src/images/svg/gameBoardBackground.svg
  src/images/svg/gameBoardFrame.svg
  src/images/svg/gameTitle.svg
  src/images/test.gif
Labels: ⛏Refactor

#254 김민주: <api> Exit API 수정
  src/pages/gameroom/GameRoom.jsx
Labels: 📬API

#255 Deploy
  src/components/chat/Chat.jsx
  src/components/community/communityCard/CommunityCard.jsx
  src/components/community/communityCard/style.scss
  src/components/community/communityFix/CommunityFix.jsx
  src/components/community/communityList/CommunityList.jsx
  src/components/community/communityList/style.scss
  src/components/gameBoard/GameBoard.jsx
  src/components/gameRuleBoard/GameRuleBoard.jsx
  src/components/gameRuleBoard/style.scss
  src/components/lobbyHeader/LobbyHeader.jsx
  src/components/lobbyHeader/style.scss
  src/components/rewardAlert/RewardAlert.jsx
  src/components/rewardAlert/style.scss
  src/components/roomList/RoomList.jsx
  src/components/roomList/style.scss
  src/components/setting/SettingBoard.jsx
  src/components/setting/style.scss
  src/components/sign/formSignIn/FormSignIn.jsx
  src/components/socialHeader/DetailSocialHeader.jsx
  src/components/socialHeader/SocialHeader.jsx
  src/components/videoroom/video/Video.js
  src/images/png/chatOutputBox.png
  src/images/png/crown.png
  src/images/png/gameBoardFrame.png
  src/images/png/gameRuleFrame.png
  src/images/png/gameTitle.png
  src/images/png/rewardIcon.png
  src/images/png/settingFrame.png
  src/images/rooms/room_01.jpg
  src/images/rooms/room_02.jpg
  src/images/rooms/room_03.jpg
  src/images/rooms/room_04.jpg
  src/images/rooms/room_05.jpg
  src/images/rooms/room_06.jpg
  src/images/svg/chatOutputBox.svg
  src/images/svg/crown.svg
  src/images/svg/gameBoardBackground.svg
  src/images/svg/gameBoardFrame.svg
  src/images/svg/gameTitle.svg
  src/images/svg/icCommentsIcon.svg
  src/images/svg/icQuestion.svg
  src/images/test.gif
  src/pages/gameroom/GameRoom.jsx
  src/pages/social/Write.jsx
Labels: 🌏Deploy

#256 김민주: <fix> 비디오 레이아웃 수정
  src/components/videoroom/video/Video.js
  src/components/videoroom/video/style.scss
Labels: 🐞Bug

#259 정건희: <fix> 게임 룰 버튼 클릭 영역 수정
  src/components/gameRuleBoard/GameRuleBoard.jsx
  src/components/lobbyHeader/LobbyHeader.jsx
  src/components/socialHeader/SocialHeader.jsx
Labels: 🐞Bug

#257 김민주: <fix> 필터 변경 시 페이지 초기화 되지 않아 발생하는 출력오류 수정
  src/components/roomList/RoomList.jsx
  src/components/roomList/style.scss
Labels: 🐞Bug

#260 Deploy
  src/components/community/communityCard/style.scss
  src/components/community/communityList/CommunityList.jsx
  src/components/community/communityList/style.scss
  src/components/gameRuleBoard/GameRuleBoard.jsx
  src/components/lobbyHeader/LobbyHeader.jsx
  src/components/roomList/RoomList.jsx
  src/components/roomList/style.scss
  src/components/socialHeader/SocialHeader.jsx
  src/components/videoroom/video/Video.js
  src/components/videoroom/video/style.scss
Labels: 🌏Deploy

#262 Deploy
  src/components/lobbyHeader/LobbyHeader.jsx
  src/components/socialHeader/SocialHeader.jsx
  src/pages/gameroom/GameRoom.jsx
Labels: 🌏Deploy

#264 정건희: <refactor> 마이페이지 css 모듈화
  src/components/myPage/myPageForm/MyPageForm.jsx
  src/components/myPage/myPageForm/style.module.scss
  src/components/myPage/myPageRecord/MyPageRecord.jsx
  src/components/myPage/myPageRecord/style.module.scss
  src/components/myPage/myPageReward/MyPageReward.jsx
  src/components/myPage/myPageReward/style.module.scss
  src/components/myPage/myPageRewardItem/MyPageRewardItem.jsx
  src/components/myPage/myPageRewardItem/style.module.scss
  src/components/myPage/myPageSignOff/MyPageSignOff.jsx
  src/components/myPage/myPageSignOff/style.module.scss
  src/components/myPage/myPageSignOut/MyPageSignOut.jsx
  src/components/myPage/myPageSignOut/style.module.scss
Labels: ⛏Refactor
