Repository HangHae-TheFinalProject/FrontEnd, pull requests merged in 2022-11, with the labels that each got.

#1 김민주: <feature> Element Modal 추가
  src/elements/modal/Modal.js
  src/elements/modal/ModalPortal.js
  src/elements/modal/style.scss
Labels: enhancement

#11 김민주: <feature> 화상채팅 API 연결
  package.json
  public/index.html
  src/App.js
  src/components/videoroom/components/VideoRoomComponent.css
  src/components/videoroom/components/VideoRoomComponent.js
  src/components/videoroom/components/chat/ChatComponent.css
  src/components/videoroom/components/chat/ChatComponent.js
  src/components/videoroom/components/dialog-extension/DialogExtension.css
  src/components/videoroom/components/dialog-extension/DialogExtension.js
  src/components/videoroom/components/stream/OvVideo.js
  src/components/videoroom/components/stream/StreamComponent.css
  src/components/videoroom/components/stream/StreamComponent.js
  src/components/videoroom/components/toolbar/ToolbarComponent.css
  src/components/videoroom/components/toolbar/ToolbarComponent.js
  src/components/videoroom/layout/openvidu-layout.js
  src/components/videoroom/models/user-model.js
  src/pages/GameRoom.jsx
  src/pages/Main.jsx
  src/pages/gameroom/GameRoom.jsx
  src/pages/gameroom/style.scss
  src/registerServiceWorker.js
  src/shared/Router.jsx
Labels: ✨Feature, 📬API

#13 신혜정 : <Feature> signup 기능 구현
  src/components/formSignUp/FormSignUp.jsx
  src/components/formSignUp/style.js
  src/hooks/useInput.js
  src/pages/SignUp.jsx
Labels: ✨Feature

#17 신혜정 : <Feature> Signin 기능 구현
  src/components/formSignIn/FormSignIn.jsx
  src/components/formSignIn/style.js
  src/pages/SignIn.jsx
Labels: ✨Feature

#19 신혜정 : <Feature/API> signin 수정
  package.json
  src/components/formSignIn/FormSignIn.jsx
  src/components/googleLogin/GoogleLogin.jsx
Labels: ✨Feature, 📬API

#18 신혜정 : <feature> Logout #12
  src/commponents/formLogOut/FormLogOut.jsx
  src/commponents/formLogOut/style.js
  src/pages/Main.jsx
  src/shared/Request.js
Labels: ✨Feature

#22 김민주: <feature> #21 버튼으로 제어하는 Mute 기능 작성
  src/components/videoroom/components/VideoRoomComponent.js
  src/components/videoroom/components/stream/OvVideo.js
  src/components/videoroom/components/stream/StreamComponent.js
  src/components/videoroom/components/toolbar/ToolbarComponent.js
Labels: ✨Feature

#23 김민주: <feature> Video custom
  src/components/videoroom/components/VideoRoomComponent.css
  src/components/videoroom/components/VideoRoomComponent.js
  src/components/videoroom/components/stream/OvVideo.js
  src/components/videoroom/components/stream/StreamComponent.css
  src/components/videoroom/components/stream/StreamComponent.js
  src/components/videoroom/components/stream/StreamComponent.scss
  src/index.scss
Labels: ✨Feature, 🎨HTML&CSS

#28 김민주 <style>: Video Frame svg 파일추가
  src/images/svg/nicknameBackground.svg
  src/images/svg/nicknameFrame.svg
  src/images/svg/videoFrame.svg
Labels: 🎨HTML&CSS

#25 신혜정 : <css> signup css적용
  src/components/formSignUp/FormSignUp.jsx
  src/components/formSignUp/style.js
  src/components/formSignUp/style.scss
Labels: 🎨HTML&CSS

#27 신혜정 : <css> signin css적용
  src/components/formSignIn/FormSignIn.jsx
  src/components/formSignIn/style.js
  src/components/formSignIn/style.scss
  src/components/googleLogin/GoogleLogin.jsx
  src/pages/Main.jsx
  src/pages/SignIn.jsx
Labels: 🎨HTML&CSS

#32 김민주 <style>: Gameroom layout
  src/components/chat/Chat.jsx
  src/components/chat/style.scss
  src/components/chatRoom/ChatRoom.jsx
  src/components/chatRoom/style.scss
  src/components/chatRoomList/ChatRoomList.jsx
  src/components/createRoomForm/CreateRoomForm.jsx
  src/components/temp_sign/TempSign.jsx
  src/components/temp_sign/style.scss
  src/components/videoroom/components/VideoRoomComponent.css
  src/components/videoroom/components/VideoRoomComponent.js
  src/components/videoroom/components/VideoRoomComponent.scss
  src/components/videoroom/layout/openvidu-layout.js
  src/index.scss
  src/pages/gameroom/GameRoom.jsx
  src/pages/gameroom/style.scss
  src/scss/_reset.scss
  src/shared/Request.js
  src/shared/Router.jsx
Labels: 🎨HTML&CSS

#33 김민주 <refactor> : video, chat Gameroom merge 및 일부 스타일 조정 #31
  src/components/gameBoard/GameBoard.jsx
  src/components/gameBoard/style.scss
  src/components/gameTimer/GameTimer.jsx
  src/components/gameTimer/style.scss
  src/components/videoroom/components/VideoRoomComponent.scss
  src/images/png/btnGameStart.png
  src/images/png/gameRoomBackground.png
  src/images/svg/gameBoardBackground.svg
  src/images/svg/gameBoardFrame.svg
  src/images/svg/timerFrame.svg
  src/pages/gameroom/GameRoom.jsx
  src/pages/gameroom/style.scss
  src/scss/_variable.scss
Labels: ⛏Refactor

#36 김민주: <fix> Modal z-index 수정
  src/elements/modal/style.scss
Labels: 🐞Bug

#37 김민주: <feature> gameroom 채팅 로직 변경
  package.json
  src/components/chat/Chat.jsx
  src/components/chatRoom/ChatRoom.jsx
  src/components/chatRoomList/ChatRoomList.jsx
  src/components/formSignIn/FormSignIn.jsx
  src/elements/modal/style.scss
  src/pages/gameroom/GameRoom.jsx
  src/pages/gameroom/style.scss
  src/shared/Request.js
Labels: ✨Feature, 📬API

#40 김민주: <style> GameRoom Camera layout 수정
  src/components/videoroom/components/VideoRoomComponent.js
  src/components/videoroom/components/VideoRoomComponent.scss
  src/components/videoroom/components/stream/StreamComponent.js
  src/components/videoroom/components/stream/StreamComponent.scss
Labels: 🎨HTML&CSS

#39 신혜정 : <fix> signup, signin 수정
  src/components/formSignIn/FormSignIn.jsx
  src/components/formSignIn/style.scss
  src/components/formSignUp/FormSignUp.jsx
  src/components/formSignUp/style.scss
  src/components/googleLogin/GoogleLogin.jsx
  src/components/googleLogin/style.scss
  src/components/videoroom/components/VideoRoomComponent.css
  src/components/videoroom/components/stream/StreamComponent.css
  src/images/svg/GoogleIcon.svg
  src/images/svg/Redicon.svg
  src/pages/Main.jsx
  src/pages/SignIn.jsx
Labels: 🐞Bug, 🎨HTML&CSS

#43 김민주: <feature> RoomList API 연결
  src/components/aRoom/ARoom.jsx
  src/components/roomList/RoomList.jsx
  src/components/roomList/style.scss
  src/pages/lobby/Lobby.jsx
  src/redux/modules/roomsSlice.js
Labels: ✨Feature, 📬API

#46 김민주: <fix> 룸 생성자는 redux 내 Room 정보가 공란인 문제 수리
  src/components/createRoomForm/CreateRoomForm.jsx
Labels: 🐞Bug

#48 김민주: <feature> GameTimer
  src/components/gameTimer/GameTimer.jsx
  src/components/gameTimer/style.scss
  src/pages/gameroom/GameRoom.jsx
Labels: ✨Feature

#50 김민주: <feature> Game Popup 추가
  src/components/gamePopup/GamePopup.jsx
  src/components/gamePopup/style.scss
  src/images/png/popupBackground.png
  src/pages/gameroom/GameRoom.jsx
Labels: ✨Feature, 🎨HTML&CSS

#53 정건희: <fix> service worker 및 roomlist 조회 오류 수정
  src/App.js
  src/components/roomList/RoomList.jsx
Labels: 🐞Bug

#54 정건희: <fix> VideoRoomComponent 사용하지 않는 모듈 주석
  src/components/videoroom/components/VideoRoomComponent.js
Labels: 🐞Bug

#55 정건희: <fix> VideoRoomComponent 사용하지 않는 모듈 주석
  src/components/videoroom/components/VideoRoomComponent.js
  src/components/videoroom/components/stream/StreamComponent.js
Labels: 🐞Bug

#57 김민주: <feature> MicControll #56
  src/components/videoroom/components/VideoRoomComponent.js
  src/pages/gameroom/GameRoom.jsx
Labels: ✨Feature

#59 정건희: <bug> roomList headers에 쿠키 담는 오류 해결, 로그인/회원가입 엔터키 입력 추가
  src/components/formSignIn/FormSignIn.jsx
  src/components/formSignUp/FormSignUp.jsx
  src/redux/modules/roomsSlice.js
  src/shared/Request.js
Labels: 🐞Bug

#61 김민주: <feature> Game staging #35
  src/components/gameBoard/GameBoard.jsx
  src/components/gameBoard/style.scss
  src/components/gamePopup/GamePopup.jsx
  src/components/gameTimer/GameTimer.jsx
  src/components/videoroom/components/VideoRoomComponent.js
  src/components/videoroom/components/stream/StreamComponent.js
  src/components/videoroom/components/stream/StreamComponent.scss
  src/images/png/btnExit.png
  src/images/png/btnGameStart.png
  src/images/png/btnReady.png
  src/images/png/btnReadyInert.png
  src/images/png/btnStart.png
  src/images/png/btnStartInert.png
  src/pages/gameroom/GameRoom.jsx
  src/pages/gameroom/style.scss
  src/redux/config/configStore.js
  src/redux/modules/gameSlice.js
  src/redux/modules/roomsSlice.js
Labels: ✨Feature

#63 김민주: <fix> 한번 더 투표 / 라이어 투표 선택 websocket 연결
  src/components/gameBoard/GameBoard.jsx
  src/pages/gameroom/GameRoom.jsx
Labels: 🐞Bug

#64 김민주: <fix> Vote/Onemore 방장만 반응하는 오류 수정
  src/pages/gameroom/GameRoom.jsx
Labels: 🐞Bug

#65 신혜정 : <style> 로비, 방만들기 모달 스타일 적용
  src/components/aRoom/ARoom.jsx
  src/components/aRoom/style.scss
  src/components/createRoomForm/CreateRoomForm.jsx
  src/components/createRoomForm/style.scss
  src/components/robbyHeader/RobbyHeader.jsx
  src/components/robbyHeader/style.scss
  src/images/png/createRoomImg 3517.png
  src/images/png/door1.png
  src/images/png/door2.png
  src/images/png/door3.png
  src/images/png/door4.png
  src/images/png/headerArrow.png
  src/images/png/headerImgGray.png
  src/images/png/lobbyBackGround.png
  src/images/png/roomMakerBtn.png
  src/images/svg/IcLock.svg
  src/images/svg/icArrowLeft.svg
  src/pages/lobby/Lobby.jsx
  src/pages/lobby/style.scss
Labels: 🎨HTML&CSS

#66 김민주: <style> 빛의계승자 font 추가
  src/components/gameBoard/GameBoard.jsx
  src/fonts/HeirofLightBold.ttf
  src/fonts/HeirofLightRegular.ttf
  src/scss/_variable.scss
Labels: 🎨HTML&CSS

#67 김민주: <style> Game Popup
  src/components/gamePopup/GamePopup.jsx
  src/components/gamePopup/style.scss
Labels: 🎨HTML&CSS

#68 김민주: <deploy> Chat & Video open / 배포테스트용
  src/pages/gameroom/GameRoom.jsx
Labels: 🌏Deploy

#71 김민주: <fix> login 직후 header에 token이 담기지 않는 오류 수정 #69
  public/index.html
  src/components/formSignIn/FormSignIn.jsx
  src/redux/modules/roomsSlice.js
  src/shared/Request.js
Labels: 🐞Bug

#75 신혜정 : <Style> lobby 스타일 수정
  src/components/roomList/RoomList.jsx
  src/components/roomList/style.scss
  src/images/svg/icArrowRight.svg
  src/pages/lobby/Lobby.jsx
Labels: 🎨HTML&CSS

#74 김민주: <feature> video 아래 usernickname표시 및 spotlight 표시 오류 수정 #72 #73
  src/components/videoroom/components/VideoRoomComponent.js
  src/components/videoroom/components/stream/StreamComponent.js
  src/components/videoroom/components/stream/StreamComponent.scss
Labels: ✨Feature

#78 김민주: <fix> 새로고침 후 token 추가 error #77
  src/shared/Request.js
Labels: 🐞Bug

#81 신혜정 : <Style> 로비, 방 만들기, 게임방 입장하기 스타일 수정
  src/components/createRoomForm/style.scss
  src/components/roomList/style.scss
  src/pages/lobby/style.scss
Labels: 🎨HTML&CSS

#80 정건희: <style> chat, gameboard css 수정
  src/components/chat/Chat.jsx
  src/components/chat/style.scss
  src/components/gameBoard/GameBoard.jsx
  src/components/gameBoard/style.scss
  src/images/svg/btn_send2.svg
  src/images/svg/chatOutputBox.svg
  src/images/svg/gameBoardBackground.svg
  src/images/svg/gameBoardFrame.svg
  src/pages/gameroom/style.scss
Labels: 🎨HTML&CSS

#83 신혜정 : <Style> lobby 비밀번호 모달 스타일 적용
  src/components/aRoom/ARoom.jsx
  src/components/aRoom/style.scss
  src/components/createRoomForm/CreateRoomForm.jsx
  src/images/png/passwordLayout.png
Labels: 🎨HTML&CSS

#84 김민주: <fix> 비디오/마이크 접근 오류 시 게임룸 입장 차단
  src/components/aRoom/ARoom.jsx
  src/pages/lobby/Lobby.jsx
  src/redux/modules/gameSlice.js
Labels: 🐞Bug

#86 김민주: <fix> spotlight mute 오류 수정
  src/pages/gameroom/GameRoom.jsx
Labels: 🐞Bug

#87 김민주: <fix> spotlight Mute & Unmute 테스트
  src/components/gamePopup/GamePopup.jsx
  src/components/gamePopup/style.scss
  src/pages/gameroom/GameRoom.jsx
  src/redux/modules/gameSlice.js
Labels: 🐞Bug

#88 김민주: <fix> login 상태에서 main 접속 시 lobby로 이동하도록 변경
  src/pages/Main.jsx
  src/pages/gameroom/GameRoom.jsx
Labels: 🐞Bug

#89 김민주: <fix> 유저에게 보이는 이름은 '#000' 태그 제거
  src/components/chat/Chat.jsx
  src/components/formSignIn/FormSignIn.jsx
  src/components/gamePopup/GamePopup.jsx
  src/components/videoroom/components/stream/StreamComponent.js
  src/pages/lobby/Lobby.jsx
Labels: 🐞Bug

#90 김민주: <fix> 진행중 게임에 입장할 수 없도록 수정
  src/components/aRoom/ARoom.jsx
Labels: 🐞Bug

#91 김민주: <style> GameRoom Layout 수정
  src/pages/gameroom/GameRoom.jsx
  src/pages/gameroom/style.scss
Labels: 🎨HTML&CSS

#92 김민주: <fix> Gameroom 코드 정리, API 주소 변경
  src/components/gamePopup/GamePopup.jsx
  src/components/gameTimer/GameTimer.jsx
  src/components/videoroom/components/VideoRoomComponent.css
  src/components/videoroom/components/chat/ChatComponent.css
  src/components/videoroom/components/chat/ChatComponent.js
  src/components/videoroom/components/dialog-extension/DialogExtension.css
  src/components/videoroom/components/dialog-extension/DialogExtension.js
  src/components/videoroom/components/stream/StreamComponent.css
  src/components/videoroom/components/toolbar/ToolbarComponent.css
  src/components/videoroom/components/toolbar/ToolbarComponent.js
  src/pages/gameroom/GameRoom.jsx
  src/redux/modules/gameSlice.js
Labels: 🐞Bug

#93 김민주: <fix> Redux 내 lier 변수명 및 관련 변수명 변경
  src/components/gamePopup/GamePopup.jsx
  src/components/gameTimer/GameTimer.jsx
  src/pages/gameroom/GameRoom.jsx
  src/redux/modules/gameSlice.js
Labels: 🐞Bug

#94 김민주: <fix> 다음 스테이지에서 음소거가 풀리지 않는 오류 수정
  src/components/gamePopup/GamePopup.jsx
  src/pages/gameroom/GameRoom.jsx
Labels: 🐞Bug

#95 김민주: <test> spotlight 시간 임시 단축
  src/pages/gameroom/GameRoom.jsx
Labels: ✅Test

#96 김민주: <fix> Spotlight 표시 사라지지 않는 오류 수정
  src/pages/gameroom/GameRoom.jsx
Labels: 🐞Bug

#97 김민주: <feature> 게임룸 입장 전 디바이스 체크 Lobby > GameRoom 진입 직후로 변경
  src/components/aRoom/ARoom.jsx
  src/pages/gameroom/GameRoom.jsx
  src/pages/lobby/Lobby.jsx
Labels: ✨Feature

#98 김민주: <feature> 방제목 공란체크/기본 방제목
  src/components/createRoomForm/CreateRoomForm.jsx
Labels: ✨Feature

#99 김민주: <fix> 초기 방제목 Input value로 인식 못하는 오류 수정
  src/components/createRoomForm/CreateRoomForm.jsx
Labels: 🐞Bug

#101 정건희: <feature> 댓글 기본 기능 및 css 적용
  src/components/comments/commentItem/CommentItem.jsx
  src/components/comments/commentItem/style.scss
  src/components/comments/commentPost/CommentPost.jsx
  src/components/comments/commentPost/style.scss
  src/components/comments/commentsForm/CommentsForm.jsx
  src/components/comments/commentsForm/style.scss
  src/components/comments/commentsList/CommentsList.jsx
  src/scss/_variable.scss
Labels: ✨Feature, 🎨HTML&CSS

#102 정건희: <fix> Lobby 컴포넌트 삭제 된 코드 추가
  src/pages/lobby/Lobby.jsx
Labels: 🐞Bug

#104 김민주: <fix> Record Init 값 정상 표시되지 않는 오류 수정
  src/components/myPage/myPageRecord/MyPageRecord.jsx
Labels: 🐞Bug

#105 김민주: <fix> comment 추가/수정/삭제 시 State 관리
  src/components/comments/commentItem/CommentItem.jsx
  src/components/comments/commentPost/CommentPost.jsx
  src/components/comments/commentsForm/CommentsForm.jsx
  src/components/comments/commentsList/CommentsList.jsx
Labels: 🐞Bug

#106 정건희: <feature> chat 입장 메세지 코드 추가
  src/components/chat/Chat.jsx
Labels: ✨Feature

#107 김민주: <feature> 게임 바보모드 추가
  src/components/gameBoard/GameBoard.jsx
  src/pages/gameroom/GameRoom.jsx
Labels: ✨Feature

#109 김민주: <feature> Gameroom 카테고리 기능 추가
  src/components/roomList/RoomList.jsx
  src/redux/modules/roomsSlice.js
Labels: ✨Feature

#108 정건희: <style> chat 내가 작성한 채팅 메세지 스타일 적용
  src/components/chat/Chat.jsx
  src/components/chat/style.scss
Labels: 🎨HTML&CSS

#110 김민주: <feature> 입장메세지 sender 표시 삭제
  src/components/chat/Chat.jsx
Labels: ✨Feature

#113 정건희: <style> 마이페이지 전적 디자인 수정 반영, 업적 기본 css 적용
  src/components/myPage/myPageForm/MyPageForm.jsx
  src/components/myPage/myPageForm/style.scss
  src/components/myPage/myPageRecord/MyPageRecord.jsx
  src/components/myPage/myPageRecord/style.scss
  src/components/myPage/myPageReward/MyPageReward.jsx
  src/components/myPage/myPageReward/style.scss
  src/components/myPage/myPageRewardItem/MyPageRewardItem.jsx
  src/components/myPage/myPageRewardItem/style.scss
  src/components/myPage/myPageSignOff/MyPageSignOff.jsx
  src/components/myPage/myPageSignOff/style.scss
  src/components/myPage/myPageSignOut/MyPageSignOut.jsx
  src/components/myPage/myPageSignOut/style.scss
  src/images/svg/activeAlongWithTheGods.svg
  src/images/svg/activeFirstWin.svg
  src/images/svg/activeFiveSerialLose.svg
  src/images/svg/activeFortitude.svg
  src/images/svg/activeJoyOfWin.svg
  src/images/svg/activeLierHunter.svg
  src/images/svg/activeSpeedOfLight.svg
  src/images/svg/activeTripleNine.svg
  src/images/svg/icArrowLeft2.svg
  src/images/svg/icArrowRight2.svg
  src/images/svg/inActiveAlongWithTheGods.svg
  src/images/svg/inActiveFirstWin.svg
  src/images/svg/inActiveFiveSerialLose.svg
  src/images/svg/inActiveFortitude.svg
  src/images/svg/inActiveJoyOfWin.svg
  src/images/svg/inActiveLierHunter.svg
  src/images/svg/inActiveSpeedOfLight.svg
  src/images/svg/inActiveTripleNine.svg
Labels: 🎨HTML&CSS

#111 김민주: <refactor> Videoroom 불필요한 컴포넌트 삭제 및 컴포넌트 명 변경
  src/components/videoroom/components/stream/StreamComponent.js
  src/components/videoroom/layout/openvidu-layout.js
  src/components/videoroom/video/Video.js
  src/components/videoroom/video/style.scss
  src/components/videoroom/videoRoom/VideoRoom.js
  src/components/videoroom/videoRoom/style.scss
  src/components/videoroom/videoRoom/userModel.js
  src/pages/gameroom/GameRoom.jsx
Labels: ⛏Refactor

#112 김민주: <refactor> 불필요한 console.log 삭제 / import 정렬
  src/components/formSignIn/FormSignIn.jsx
  src/components/formSignUp/FormSignUp.jsx
  src/pages/Main.jsx
  src/shared/Request.js
Labels: ⛏Refactor

#114 정건희: <fix> 업적 조회 임시 주석
  src/components/myPage/myPageForm/MyPageForm.jsx
Labels: 🐞Bug
